import { demoImages } from "./demo-images";

export type Brand =
  | "Apple"
  | "Samsung"
  | "Google"
  | "Xiaomi"
  | "OnePlus"
  | "Sony"
  | "Oppo"
  | "Honor";

export type Product = {
  slug: string;
  name: string;
  brand: Brand;
  series: string;
  tagline: string;
  priceLabel: string;
  storage: string[];
  colors: string[];
  specs: string[];
  featured?: boolean;
  image: string;
};

export const products: Product[] = [
  {
    slug: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "El flagship absoluto. Pantalla, batería y cámara al límite.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB", "2 TB"],
    colors: ["Negro Titanio", "Blanco Titanio", "Azul Titanio", "Naranja Titanio"],
    specs: ["Chip A19 Pro", "Sistema de cámara Pro", "Pantalla Super Retina XDR", "Titanium"],
    featured: true,
    image: demoImages.titanium,
  },
  {
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "Potencia profesional en un tamaño perfecto.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Blanco Titanio", "Azul Titanio"],
    specs: ["Chip A19 Pro", "Cámara Pro", "ProMotion 120 Hz", "USB-C"],
    featured: true,
    image: demoImages.iphonePro,
  },
  {
    slug: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "Nueva generación. Ligero, rápido y brillante.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Negro", "Blanco", "Azul", "Rosa"],
    specs: ["Chip A19", "Cámara dual avanzada", "Dynamic Island", "Ceramic Shield"],
    featured: true,
    image: demoImages.iphoneStudio,
  },
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Pro Max de la generación anterior, precio imbatible.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Desierto Titanio", "Natural Titanio", "Blanco Titanio"],
    specs: ["Chip A18 Pro", "Cámara 48 MP", "Control de cámara", "Titanium"],
    image: demoImages.iphoneDark,
  },
  {
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Rendimiento Pro en formato compacto.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Desierto Titanio", "Natural Titanio", "Blanco Titanio"],
    specs: ["Chip A18 Pro", "Cámara Pro", "Action Button", "ProMotion"],
    image: demoImages.blackPhone,
  },
  {
    slug: "iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Equilibrio perfecto entre potencia y precio.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Negro", "Blanco", "Rosa", "Verde azulado", "Ultramarino"],
    specs: ["Chip A18", "Cámara Fusion 48 MP", "Botón de cámara", "USB-C"],
    image: demoImages.bluePhone,
  },
  {
    slug: "iphone-16-plus",
    name: "iPhone 16 Plus",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Más pantalla. Más batería. Misma generación.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Negro", "Blanco", "Rosa", "Verde azulado", "Ultramarino"],
    specs: ["Chip A18", "Pantalla 6.7\"", "Cámara Fusion", "USB-C"],
    image: demoImages.iphoneWhite,
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Titanium legendario a precio de oportunidad.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Azul Titanio", "Blanco Titanio", "Titanio natural"],
    specs: ["Chip A17 Pro", "Cámara 5x", "Action Button", "USB-C"],
    image: demoImages.premiumDesk,
  },
  {
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Pro sin complicaciones. Listo para lo diario y lo creativo.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Azul Titanio", "Blanco Titanio", "Titanio natural"],
    specs: ["Chip A17 Pro", "Cámara Pro", "Action Button", "USB-C"],
    image: demoImages.iphoneHands,
  },
  {
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Dynamic Island y USB-C en el esencial de Apple.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Negro", "Azul", "Verde", "Amarillo", "Rosa"],
    specs: ["Chip A16", "Cámara 48 MP", "Dynamic Island", "USB-C"],
    image: demoImages.iphoneFlat,
  },
  {
    slug: "iphone-14-pro",
    name: "iPhone 14 Pro",
    brand: "Apple",
    series: "iPhone 14",
    tagline: "Always-On y cámara Pro aún vigentes.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Negro espacial", "Plata", "Oro", "Morado intenso"],
    specs: ["Chip A16", "Always-On Display", "Cámara 48 MP", "Dynamic Island"],
    image: demoImages.glassPhone,
  },
  {
    slug: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "S Pen, zoom extremo y pantalla de referencia.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro Titanio", "Gris Titanio", "Azul Titanio", "Plata"],
    specs: ["Snapdragon elite", "S Pen", "Cámara 200 MP", "Gorilla Armor"],
    featured: true,
    image: demoImages.samsung,
  },
  {
    slug: "galaxy-s25-plus",
    name: "Galaxy S25+",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "Pantalla ampla y autonomía Galaxy.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: ["Azul marino", "Gris sombra", "Plata", "Negro"],
    specs: ["Pantalla Dynamic AMOLED 2X", "Carga rápida", "IP68", "AI Galaxy"],
    image: demoImages.flagship,
  },
  {
    slug: "galaxy-s25",
    name: "Galaxy S25",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "Compacto, potente y con IA de Samsung.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB"],
    colors: ["Azul marino", "Gris sombra", "Plata", "Negro"],
    specs: ["AI Galaxy", "Cámara triple", "IP68", "120 Hz"],
    image: demoImages.modernPhone,
  },
  {
    slug: "galaxy-z-fold6",
    name: "Galaxy Z Fold6",
    brand: "Samsung",
    series: "Galaxy Z",
    tagline: "Tablet y teléfono en un solo dispositivo.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro fantasma", "Plata sombra", "Rosa", "Azul marino"],
    specs: ["Pantalla plegable", "Multitarea", "S Pen compatible", "IPX8"],
    image: demoImages.samsungFold,
  },
  {
    slug: "galaxy-z-flip6",
    name: "Galaxy Z Flip6",
    brand: "Samsung",
    series: "Galaxy Z",
    tagline: "Estilo icónico. Formato plegable tipo clamshell.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: ["Azul sombra", "Plata sombra", "Mint", "Amarillo"],
    specs: ["Flex Window", "AI Galaxy", "Compacto", "IPX8"],
    image: demoImages.foldable,
  },
  {
    slug: "pixel-9-pro-xl",
    name: "Pixel 9 Pro XL",
    brand: "Google",
    series: "Pixel 9",
    tagline: "La mejor cámara computacional de Google.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Obsidiana", "Porcelana", "Hazel", "Rosa"],
    specs: ["Tensor G4", "Gemini Nano", "Zoom Pro", "Pantalla LTPO"],
    image: demoImages.pixel,
  },
  {
    slug: "pixel-9-pro",
    name: "Pixel 9 Pro",
    brand: "Google",
    series: "Pixel 9",
    tagline: "Pro en tamaño ideal. Foto y IA de primer nivel.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: ["Obsidiana", "Porcelana", "Hazel", "Rosa"],
    specs: ["Tensor G4", "Cámara Pro", "Magic Editor", "7 años de updates"],
    image: demoImages.cameraPhone,
  },
  {
    slug: "pixel-9",
    name: "Pixel 9",
    brand: "Google",
    series: "Pixel 9",
    tagline: "Simplicidad Google. Fotos impecables.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB"],
    colors: ["Obsidiana", "Porcelana", "Peonía", "Verde invierno"],
    specs: ["Tensor G4", "Gemini", "Carga inalámbrica", "IP68"],
    image: demoImages.silverPhone,
  },
  {
    slug: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    brand: "Xiaomi",
    series: "Xiaomi 15",
    tagline: "Óptica Leica. Flagship fotográfico.",
    priceLabel: "Consultar",
    storage: ["512 GB", "1 TB"],
    colors: ["Negro", "Blanco", "Verde"],
    specs: ["Leica Optics", "Snapdragon elite", "Carga hiper rápida", "IP68"],
    image: demoImages.premiumDesk,
  },
  {
    slug: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    series: "OnePlus",
    tagline: "Velocidad, carga y rendimiento sin fricción.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro", "Azul", "Blanco"],
    specs: ["Snapdragon elite", "Hasselblad", "Carga 100W", "OxygenOS"],
    image: demoImages.flagship,
  },
  {
    slug: "sony-xperia-1-vi",
    name: "Sony Xperia 1 VI",
    brand: "Sony",
    series: "Xperia",
    tagline: "Cine y foto profesionales en formato 21:9.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: ["Negro", "Plata", "Verde khaki"],
    specs: ["Pantalla 4K CinemaWide", "Óptica ZEISS", "3.5 mm jack", "MicroSD"],
    image: demoImages.modernPhone,
  },
  {
    slug: "oppo-find-x8-pro",
    name: "OPPO Find X8 Pro",
    brand: "Oppo",
    series: "Find X",
    tagline: "Diseño premium y cámara Hasselblad-level.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: ["Negro espacial", "Azul glaciares", "Blanco"],
    specs: ["Pantalla LTPO", "Zoom periscopio", "Carga rápida", "IP68"],
    image: demoImages.bluePhone,
  },
  {
    slug: "honor-magic7-pro",
    name: "Honor Magic7 Pro",
    brand: "Honor",
    series: "Magic",
    tagline: "AI flagship con batería y brillo extremos.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: ["Negro", "Gris lunar", "Naranja"],
    specs: ["Snapdragon elite", "Cámara AI", "Pantalla silicon-OLED", "IP68"],
    image: demoImages.blackPhone,
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}

export const brands = Array.from(new Set(products.map((p) => p.brand)));
